-- Pump Points redeem: spendable balance vs lifetime (tiers), inventory, audit.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS points_lifetime bigint NOT NULL DEFAULT 0;

UPDATE users
SET points_lifetime = GREATEST(COALESCE(points_lifetime, 0), COALESCE(points, 0))
WHERE COALESCE(points_lifetime, 0) < COALESCE(points, 0);

CREATE OR REPLACE FUNCTION public.trg_users_points_lifetime()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.points_lifetime := GREATEST(COALESCE(NEW.points_lifetime, 0), COALESCE(NEW.points, 0));
    RETURN NEW;
  END IF;

  IF NEW.points IS DISTINCT FROM OLD.points AND NEW.points > COALESCE(OLD.points, 0) THEN
    NEW.points_lifetime := COALESCE(OLD.points_lifetime, 0) + (NEW.points - COALESCE(OLD.points, 0));
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_points_lifetime_trg ON users;
CREATE TRIGGER users_points_lifetime_trg
  BEFORE INSERT OR UPDATE OF points ON users
  FOR EACH ROW
  EXECUTE PROCEDURE public.trg_users_points_lifetime();

CREATE TABLE IF NOT EXISTS public.points_redemptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  redeem_key text NOT NULL,
  address text NOT NULL,
  item_id text NOT NULL,
  cost_pts integer NOT NULL CHECK (cost_pts > 0),
  status text NOT NULL DEFAULT 'completed'
    CHECK (status = ANY (ARRAY['completed'::text, 'failed'::text, 'reversed'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT points_redemptions_redeem_key_key UNIQUE (redeem_key)
);

CREATE INDEX IF NOT EXISTS idx_points_redemptions_address_created
  ON public.points_redemptions (address, created_at DESC);

CREATE TABLE IF NOT EXISTS public.points_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address text NOT NULL,
  item_id text NOT NULL,
  status text NOT NULL DEFAULT 'active'
    CHECK (status = ANY (ARRAY['active'::text, 'consumed'::text, 'expired'::text])),
  redemption_id bigint REFERENCES public.points_redemptions (id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_points_inventory_address_status
  ON public.points_inventory (address, status, created_at DESC);

CREATE OR REPLACE FUNCTION public.launchpad_redeem_points(
  p_address text,
  p_item_id text,
  p_cost_pts integer,
  p_redeem_key text,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE(
  status text,
  points_spent integer,
  spendable_points bigint,
  lifetime_points bigint,
  inventory_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_address text := lower(p_address);
  v_existing points_redemptions%ROWTYPE;
  v_points bigint;
  v_lifetime bigint;
  v_inv_id bigint;
  v_redemption_id bigint;
BEGIN
  IF v_address IS NULL OR v_address = '' THEN
    RAISE EXCEPTION 'address is required';
  END IF;
  IF p_item_id IS NULL OR btrim(p_item_id) = '' THEN
    RAISE EXCEPTION 'item_id is required';
  END IF;
  IF p_redeem_key IS NULL OR btrim(p_redeem_key) = '' THEN
    RAISE EXCEPTION 'redeem_key is required';
  END IF;
  IF p_cost_pts IS NULL OR p_cost_pts <= 0 THEN
    RAISE EXCEPTION 'cost_pts must be positive';
  END IF;

  SELECT * INTO v_existing
  FROM points_redemptions
  WHERE redeem_key = p_redeem_key
  LIMIT 1;

  IF FOUND THEN
    SELECT COALESCE(u.points, 0), COALESCE(u.points_lifetime, u.points, 0)
      INTO v_points, v_lifetime
    FROM users u WHERE u.address = v_address;

    SELECT i.id INTO v_inv_id
    FROM points_inventory i
    WHERE i.redemption_id = v_existing.id
    ORDER BY i.id DESC
    LIMIT 1;

    status := 'IDEMPOTENT';
    points_spent := v_existing.cost_pts;
    spendable_points := COALESCE(v_points, 0);
    lifetime_points := COALESCE(v_lifetime, 0);
    inventory_id := v_inv_id;
    RETURN NEXT;
    RETURN;
  END IF;

  INSERT INTO users (address, last_active)
  VALUES (v_address, now())
  ON CONFLICT (address) DO UPDATE SET last_active = EXCLUDED.last_active;

  SELECT COALESCE(points, 0), COALESCE(points_lifetime, points, 0)
    INTO v_points, v_lifetime
  FROM users
  WHERE address = v_address
  FOR UPDATE;

  IF v_points < p_cost_pts THEN
    RAISE EXCEPTION 'insufficient_points' USING ERRCODE = 'P0001';
  END IF;

  UPDATE users
  SET points = v_points - p_cost_pts,
      last_active = now()
  WHERE address = v_address;

  INSERT INTO points_redemptions (redeem_key, address, item_id, cost_pts, status, metadata)
  VALUES (p_redeem_key, v_address, p_item_id, p_cost_pts, 'completed', COALESCE(p_metadata, '{}'::jsonb))
  RETURNING id INTO v_redemption_id;

  INSERT INTO points_inventory (address, item_id, status, redemption_id, metadata)
  VALUES (
    v_address,
    p_item_id,
    'active',
    v_redemption_id,
    COALESCE(p_metadata, '{}'::jsonb) || jsonb_build_object('cost_pts', p_cost_pts)
  )
  RETURNING id INTO v_inv_id;

  INSERT INTO points_audit_log (address, points_awarded, task_type, tx_hash, metadata)
  VALUES (
    v_address,
    -p_cost_pts,
    'REDEEM:' || p_item_id,
    'redeem:' || p_redeem_key,
    COALESCE(p_metadata, '{}'::jsonb) || jsonb_build_object(
      'redeem_key', p_redeem_key,
      'inventory_id', v_inv_id
    )
  );

  status := 'COMPLETED';
  points_spent := p_cost_pts;
  spendable_points := v_points - p_cost_pts;
  lifetime_points := v_lifetime;
  inventory_id := v_inv_id;
  RETURN NEXT;
END;
$$;

GRANT EXECUTE ON FUNCTION public.launchpad_redeem_points(text, text, integer, text, jsonb)
  TO pump_indexer, pump_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.points_redemptions TO pump_indexer, pump_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.points_inventory TO pump_indexer, pump_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pump_indexer, pump_app;
