-- Phase B/C: stats rollups, KOL marketplace, sponsored callouts
-- Run: sudo -u postgres psql -d pump_db -f db/migrations/042_kol_stats_marketplace.sql
-- Backfill: sudo -u postgres psql -d pump_db -f db/refresh/backfill_stats_rollups.sql

-- ── Token performance (peak X from launch) ─────────────────────

ALTER TABLE token_board_stats
  ADD COLUMN IF NOT EXISTS launch_mcap_zug numeric,
  ADD COLUMN IF NOT EXISTS peak_multiplier_x numeric NOT NULL DEFAULT 1;

COMMENT ON COLUMN token_board_stats.launch_mcap_zug IS 'FDV at launch (virtual reserve × supply)';
COMMENT ON COLUMN token_board_stats.peak_multiplier_x IS 'ath_market_cap_zug / launch_mcap_zug';

-- ── Per-user trade aggregates ───────────────────────────────────

CREATE TABLE IF NOT EXISTS user_trade_stats (
  address text PRIMARY KEY,
  trade_count integer NOT NULL DEFAULT 0,
  buy_count integer NOT NULL DEFAULT 0,
  sell_count integer NOT NULL DEFAULT 0,
  distinct_tokens integer NOT NULL DEFAULT 0,
  total_volume_zug numeric NOT NULL DEFAULT 0,
  first_trade_at timestamptz,
  last_trade_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (address = lower(address))
);

CREATE INDEX IF NOT EXISTS idx_user_trade_stats_volume
  ON user_trade_stats (total_volume_zug DESC);

-- ── Referral network rollups (referrer-side) ────────────────────

CREATE TABLE IF NOT EXISTS referrer_network_stats (
  referrer_address text PRIMARY KEY,
  qualified_invite_count integer NOT NULL DEFAULT 0,
  active_invitee_count_30d integer NOT NULL DEFAULT 0,
  network_volume_zug numeric NOT NULL DEFAULT 0,
  network_fee_earned_zug numeric NOT NULL DEFAULT 0,
  avg_volume_per_invitee numeric NOT NULL DEFAULT 0,
  repeat_trader_count integer NOT NULL DEFAULT 0,
  repeat_trader_rate numeric NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (referrer_address = lower(referrer_address))
);

CREATE INDEX IF NOT EXISTS idx_referrer_network_stats_volume
  ON referrer_network_stats (network_volume_zug DESC);

-- ── Hold duration aggregates ────────────────────────────────────

CREATE TABLE IF NOT EXISTS user_hold_stats (
  address text PRIMARY KEY,
  closed_lot_count integer NOT NULL DEFAULT 0,
  total_hold_seconds bigint NOT NULL DEFAULT 0,
  avg_hold_seconds numeric NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (address = lower(address))
);

CREATE TABLE IF NOT EXISTS user_position_lots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_address text NOT NULL,
  address text NOT NULL,
  opened_at timestamptz NOT NULL,
  closed_at timestamptz,
  entry_mcap_zug numeric,
  peak_multiplier_x numeric NOT NULL DEFAULT 1,
  hold_seconds bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (token_address = lower(token_address)),
  CHECK (address = lower(address))
);

CREATE INDEX IF NOT EXISTS idx_user_position_lots_open
  ON user_position_lots (address, token_address)
  WHERE closed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_user_position_lots_address
  ON user_position_lots (address, closed_at DESC NULLS FIRST);

-- ── KOL profiles & performance ────────────────────────────────

CREATE TABLE IF NOT EXISTS kol_profiles (
  address text PRIMARY KEY,
  min_price_usd numeric NOT NULL DEFAULT 10 CHECK (min_price_usd >= 0),
  is_active boolean NOT NULL DEFAULT true,
  kol_tier text NOT NULL DEFAULT 'standard'
    CHECK (kol_tier IN ('standard', 'verified')),
  bio text,
  callout_count integer NOT NULL DEFAULT 0,
  sponsored_callout_count integer NOT NULL DEFAULT 0,
  callout_hit_rate numeric NOT NULL DEFAULT 0,
  median_callout_multiplier numeric NOT NULL DEFAULT 0,
  avg_callout_multiplier numeric NOT NULL DEFAULT 0,
  accept_rate numeric NOT NULL DEFAULT 0,
  avg_response_minutes numeric,
  requests_received integer NOT NULL DEFAULT 0,
  requests_accepted integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (address = lower(address))
);

CREATE INDEX IF NOT EXISTS idx_kol_profiles_active
  ON kol_profiles (is_active, kol_tier)
  WHERE is_active = true;

-- ── Sponsored callout requests ──────────────────────────────────

CREATE TABLE IF NOT EXISTS kol_callout_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sponsor_address text NOT NULL,
  kol_address text NOT NULL,
  token_address text NOT NULL,
  price_usd numeric NOT NULL CHECK (price_usd > 0),
  escrow_amount_zug numeric NOT NULL CHECK (escrow_amount_zug > 0),
  escrow_tx_hash text,
  release_tx_hash text,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'rejected', 'expired', 'completed', 'refunded')),
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  completed_at timestamptz,
  announcement_id bigint,
  reject_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (sponsor_address = lower(sponsor_address)),
  CHECK (kol_address = lower(kol_address)),
  CHECK (token_address = lower(token_address))
);

CREATE INDEX IF NOT EXISTS idx_kol_callout_requests_kol
  ON kol_callout_requests (kol_address, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_kol_callout_requests_sponsor
  ON kol_callout_requests (sponsor_address, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kol_callout_requests_escrow_tx
  ON kol_callout_requests (escrow_tx_hash)
  WHERE escrow_tx_hash IS NOT NULL;

-- ── Sponsored callout columns on announcements ──────────────────

ALTER TABLE token_announcements
  ADD COLUMN IF NOT EXISTS is_sponsored boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS sponsor_address text;

CREATE INDEX IF NOT EXISTS idx_token_announcements_sponsored
  ON token_announcements (announcer_address, is_sponsored, created_at DESC);

-- ── Grants ──────────────────────────────────────────────────────

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pump_indexer') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON user_trade_stats TO pump_indexer;
    GRANT SELECT, INSERT, UPDATE, DELETE ON referrer_network_stats TO pump_indexer;
    GRANT SELECT, INSERT, UPDATE, DELETE ON user_hold_stats TO pump_indexer;
    GRANT SELECT, INSERT, UPDATE, DELETE ON user_position_lots TO pump_indexer;
    GRANT USAGE, SELECT ON SEQUENCE user_position_lots_id_seq TO pump_indexer;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pump_app') THEN
    GRANT SELECT ON user_trade_stats TO pump_app;
    GRANT SELECT ON referrer_network_stats TO pump_app;
    GRANT SELECT ON user_hold_stats TO pump_app;
    GRANT SELECT ON user_position_lots TO pump_app;
    GRANT SELECT, INSERT, UPDATE ON kol_profiles TO pump_app;
    GRANT SELECT, INSERT, UPDATE ON kol_callout_requests TO pump_app;
  END IF;
END $$;
