import type { LucideIcon } from "lucide-react";
import {
  Activity,
  ArrowLeftRight,
  BarChart3,
  CircleDollarSign,
  Clock,
  Coins,
  Crown,
  Gem,
  History,
  LayoutGrid,
  Percent,
  Rocket,
  Sparkles,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  Wallet,
  Zap,
} from "lucide-react";
import { AirdropParachute } from "@/components/icons/AirdropParachute";

/** Lucide icons for metrics, sections, and table headers. */
export const MetricIcons = {
  mcap: CircleDollarSign,
  vol24h: Activity,
  ath: TrendingUp,
  age: Clock,
  txns: ArrowLeftRight,
  traders: Users,
  participants: Users,
  change1h: Zap,
  change6h: BarChart3,
  change24h: Percent,
  timeAsKing: Crown,
  topGainer: TrendingUp,
  topVolume: BarChart3,
  mostTrades: ArrowLeftRight,
  koth: Crown,
  liveLeader: Crown,
  recent: History,
  exploreCoins: LayoutGrid,
  exploreAirdrops: AirdropParachute,
  airdrops: AirdropParachute,
  totalRewards: Coins,
  largestPool: Trophy,
  endingSoon: Timer,
  rewardPool: Coins,
  progress: Timer,
  poolToken: Gem,
  status: Sparkles,
  featured: Sparkles,
  activity: Activity,
  holdings: Wallet,
  portfolio: Wallet,
  portfolioValue: CircleDollarSign,
  netPnl: TrendingUp,
  missions: Target,
  pumpPoints: Target,
  launch: Rocket,
  kingOfHill: Crown,
  graph: Activity,
} as const satisfies Record<string, LucideIcon>;
