export const KOL_MARKET_COPY = {
  pageTitle: "KOL Market",
  pageKicker: "Sponsored callouts",
  pageDescription:
    "Pay verified creators to call out your token. Followers get notified — no holdings required.",
  exploreTab: "Explore",
  inboxTab: "Requests",
  settingsTab: "List yourself",
  whyFollowTitle: "Why follow a KOL",
  whyFollowBody:
    "Track median callout X, network volume, repeat traders, and hold time before you copy.",
  whySponsorTitle: "Why sponsor a callout",
  whySponsorBody:
    "Reach a creator's followers instantly. Payment is escrowed until they accept and publish.",
  verifiedBadge: "Verified KOL",
  standardBadge: "KOL",
  emptyExplore: "No KOL listings yet. Be the first — open List yourself.",
  emptyInbox: "No pending sponsored requests.",
  minPriceLabel: "Min price",
  followersLabel: "Followers",
  calloutsLabel: "Callouts",
  medianXLabel: "Median X",
  hitRateLabel: "Hit rate",
  networkVolLabel: "Network vol.",
  repeatRateLabel: "Repeat traders",
  avgHoldLabel: "Avg hold",
  acceptRateLabel: "Accept rate",
  requestCta: "Request callout",
  acceptCta: "Accept",
  rejectCta: "Decline",
  saveListingCta: "Save listing",
  listingActive: "Accepting requests",
  listingPaused: "Paused",
  minPriceHint: "USD minimum per sponsored callout",
  bioLabel: "Bio (optional)",
  tokenAddressLabel: "Token contract",
  yourTokenLabel: "Your token",
  yourTokenHint: "Only tokens you launched can request a paid callout.",
  selectTokenPlaceholder: "Select a launched token",
  noLaunchedTokens: "You haven’t launched a token yet.",
  launchTokenCta: "Launch a token",
  notTokenCreatorError: "You can only request callouts for tokens you launched",
  payAndSendCta: "Pay & send request",
  connectWallet: "Connect wallet to continue",
  loadError: "Could not load KOL market.",
  requestSent: "Request sent — waiting for KOL.",
  sponsoredLabel: "Sponsored callout",
} as const;

export type KolMarketTab = "explore" | "inbox" | "settings";
