import type { PumpIconDefinition } from "@/lib/icons";
import {
  faActivity,
  faArrowLeftRight,
  faAirdropParachute,
  faBarChart3,
  faCircleDollarSign,
  faClock,
  faCoins,
  faCrown,
  faGem,
  faHistory,
  faLayoutGrid,
  faPercent,
  faRocket,
  faSparkles,
  faTarget,
  faTimer,
  faTrendingUp,
  faTrophy,
  faUsers,
  faWallet,
  faZap,
} from "@/lib/pump-icons";

/** CDS Icons for metrics, sections, and table headers. */
export const MetricIcons = {
  mcap: faCircleDollarSign,
  vol24h: faActivity,
  ath: faTrendingUp,
  age: faClock,
  txns: faArrowLeftRight,
  traders: faUsers,
  participants: faUsers,
  change1h: faZap,
  change6h: faBarChart3,
  change24h: faPercent,
  timeAsKing: faCrown,
  topGainer: faTrendingUp,
  topVolume: faBarChart3,
  mostTrades: faArrowLeftRight,
  koth: faCrown,
  liveLeader: faCrown,
  recent: faHistory,
  exploreCoins: faLayoutGrid,
  exploreAirdrops: faAirdropParachute,
  airdrops: faAirdropParachute,
  totalRewards: faCoins,
  largestPool: faTrophy,
  endingSoon: faTimer,
  rewardPool: faCoins,
  progress: faTimer,
  poolToken: faGem,
  status: faSparkles,
  featured: faSparkles,
  activity: faActivity,
  holdings: faWallet,
  portfolio: faWallet,
  portfolioValue: faCircleDollarSign,
  netPnl: faTrendingUp,
  missions: faTarget,
  pumpPoints: faTarget,
  launch: faRocket,
  kingOfHill: faCrown,
  graph: faActivity,
} as const satisfies Record<string, PumpIconDefinition>;
